# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NUnHFY4Yo4NC4JM4ksAPHMCDAETeDU-n
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/hepatitis.csv')
df

""" Exploratory Data Analysis"""

df.info()

df.describe()

df.isnull().sum()

#len(df[df=="?"])
(df == '?').sum().sum()

x = len(df[df["alk"]=="?"])
y = len(df[df["protime"]=="?"])
z=x+y
z

#len(df[df["histology"]=="?"])
w = len(df[df["albu"]=="?"])
a = w+z
b = len(df[df["sgot"]=="?"])
c= b+a
d= len(df[df["bili"]=="?"])
e=d+c
f = len(df[df["varices"]=="?"])
g = e+f
h = len(df[df["ascites"]=="?"])
i =h+g
j = len(df[df["spiders"]=="?"])
k = j+ i
n = len(df[df["spleen"]=="?"])
o = k+n
p = len(df[df["liverFirm"]=="?"])
q = o+p
r = len(df[df["liverBig"]=="?"])
s = q+r
t = len(df[df["anorexia"]=="?"])
u = t+s
v = len(df[df["malaise"]=="?"])
w1 = u+v
x = len(df[df["fatigue"]=="?"])
y1 = w1+x
z1 = len(df[df["antivirals"]=="?"])
z2 = z1+y1
z3 = len(df[df["steroid"]=="?"])
z4  = z2+z3
z5 = len(df[df["gender"]=="?"])
z6 = z4+z5
#len(df[df["age"]=="?"])
#len(df[df["target"]=="?"])
z6

df["alk"] = df["alk"].replace("?", np.nan)
df["protime"] = df["protime"].replace("?", np.nan)
df["albu"] = df["albu"].replace("?", np.nan)
df["sgot"] = df["sgot"].replace("?", np.nan)
df["bili"] = df["bili"].replace("?", np.nan)
df["varices"] = df["varices"].replace("?", np.nan)
df["ascites"] = df["ascites"].replace("?", np.nan)
df["spiders"] = df["spiders"].replace("?", np.nan)
df["spleen"] = df["spleen"].replace("?", np.nan)
df["liverFirm"] = df["liverFirm"].replace("?", np.nan)
df["liverBig"] = df["liverBig"].replace("?", np.nan)
df["anorexia"] = df["anorexia"].replace("?", np.nan)
df["malaise"] = df["malaise"].replace("?", np.nan)
df["fatigue"] = df["fatigue"].replace("?", np.nan)
df["antivirals"] = df["antivirals"].replace("?", np.nan)
df["steroid"] = df["steroid"].replace("?", np.nan)
df["gender"] = df["gender"].replace("?", np.nan)

(df == '?').sum().sum()

df["alk"].value_counts().sum()

for col in df.columns:
    print( col,':', df[col].nunique() )

object_columns = df.select_dtypes(include='object').columns
df[object_columns] = df[object_columns].apply(pd.to_numeric, errors='coerce')
df.info()

for col in df.columns:
    df[col].fillna(df[col].mean(), inplace=True)

data = df.drop(["ID"], axis=1)

x = df.drop("target", axis=1)
y = df["target"]

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y , test_size=0.41,random_state=40)

from sklearn.svm import SVC
model = SVC()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
model.score(x_test, y_test)